#line 2 "dtd_parse.c"
/* Include this before everything else, for various large-file definitions */
#include "config.h"

#line 6 "dtd_parse.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE Dtd_Parse_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via Dtd_Parse_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void Dtd_Parse_restart (FILE *input_file ,yyscan_t yyscanner );
void Dtd_Parse__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE Dtd_Parse__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void Dtd_Parse__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void Dtd_Parse__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void Dtd_Parse_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void Dtd_Parse_pop_buffer_state (yyscan_t yyscanner );

static void Dtd_Parse_ensure_buffer_stack (yyscan_t yyscanner );
static void Dtd_Parse__load_buffer_state (yyscan_t yyscanner );
static void Dtd_Parse__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER Dtd_Parse__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE Dtd_Parse__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE Dtd_Parse__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE Dtd_Parse__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *Dtd_Parse_alloc (yy_size_t ,yyscan_t yyscanner );
void *Dtd_Parse_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void Dtd_Parse_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer Dtd_Parse__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        Dtd_Parse_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Dtd_Parse__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        Dtd_Parse_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Dtd_Parse__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define Dtd_Parse_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[219] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    3,    3,
        0,    0,   57,   56,    1,   56,   56,   56,   48,   49,
       44,   46,   47,   55,   56,   23,   45,   55,   55,   55,
       55,   55,   55,   50,   51,   52,   56,   56,   56,   14,
        1,   56,   16,   56,   18,    1,   18,   19,    1,   20,
        3,    1,    4,    7,    1,    8,    1,    0,   53,    0,
        0,    0,    0,    0,    0,    0,   54,   55,   22,    9,
       55,   55,   55,   55,   55,   55,   55,   31,   55,   55,
        0,   13,    0,   14,    1,   15,   16,   21,   17,    0,

       19,    1,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   28,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   12,    0,    5,    0,    0,    0,    0,    0,
        0,    2,    0,   55,   55,   55,   55,   55,   55,   55,
       55,   55,    0,    0,    0,    0,    0,    0,    0,    0,
       55,   39,   55,   55,   30,   55,   32,   55,   55,    0,
       29,    0,   41,    0,    0,    0,    0,   55,   55,   55,
       55,   36,   33,   55,   55,    0,    0,    0,   27,    0,
        0,   24,   26,   25,   55,   34,   55,    0,   40,   43,
        0,    0,   37,   35,   38,    0,   42,    0,    0,    6,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   10,   11,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    1,    1,    8,    9,
       10,   11,   12,   13,   14,    1,    1,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
       18,   19,   20,    1,   21,   15,   22,   23,   24,   25,
       15,   15,   26,   15,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   15,   15,   38,   39,   15,
       40,    1,   41,    1,   42,    1,   43,   44,   45,   15,

       46,   15,   15,   47,   48,   15,   49,   50,   15,   51,
       52,   53,   15,   54,   55,   56,   15,   15,   57,   15,
       15,   15,    1,   58,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[59] =
    {   0,
        1,    2,    3,    1,    1,    4,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1
    } ;

static yyconst flex_uint16_t yy_base[233] =
    {   0,
        0,    3,    7,    0,   64,   68,   71,   74,   87,   90,
      125,  183,   93,   96,   99,  113,  144,  149,  154,  157,
      160,  202,  431,  432,  120,  424,  185,  421,  432,  432,
      432,  432,  432,    0,  149,  432,  432,   50,  405,  396,
      144,  403,   75,  432,  432,  432,    0,  406,  376,    0,
      173,  404,    0,  403,  432,  178,  206,    0,  211,  432,
      432,  224,  407,  432,  227,  432,  230,  414,  432,  396,
      394,  391,  387,  393,  390,  405,  432,    0,  221,  432,
      373,  375,  389,  387,  384,  375,  370,  371,  368,  367,
      383,  432,  347,    0,  236,  432,    0,  432,  432,  230,

        0,  240,  381,  378,  373,  359,  364,  372,  361,  379,
      245,  361,    0,  363,  354,  353,  359,  351,  360,  361,
      353,  362,  432,  336,  432,  345,  359,  355,  350,  356,
      339,  432,  339,  348,  352,  333,  347,  331,  333,  343,
      340,  330,  310,  343,  326,  339,  335,  324,  333,  337,
      322,    0,  323,  318,    0,   43,  309,  269,  266,  244,
      432,  262,  432,  263,  265,  251,  248,  247,  258,  242,
      253,    0,    0,  246,  238,  225,  231,  243,  432,  239,
      236,    0,    0,    0,  225,  224,  228,  200,  432,  432,
      230,  221,    0,    0,    0,  199,  432,  217,  229,  432,

       59,  168,  164,  171,  157,  155,  122,  114,   97,   92,
       75,   66,   61,   57,   37,  432,  432,  432,  296,  301,
      306,  311,  316,  321,  326,  331,  336,   78,  341,  346,
       74,  351
    } ;

static yyconst flex_int16_t yy_def[233] =
    {   0,
      219,  219,  218,    3,  219,  219,  220,  220,  219,  219,
      221,  221,  222,  222,  223,  223,  219,  219,  224,  224,
      225,  225,  218,  218,  218,  226,  218,  227,  218,  218,
      218,  218,  218,  228,  218,  218,  218,  228,  228,  228,
      228,  228,  228,  218,  218,  218,  229,  218,  218,  230,
      230,  218,  231,  218,  218,  218,  218,  232,  232,  218,
      218,  218,  218,  218,  218,  218,  218,  226,  218,  218,
      218,  218,  218,  218,  218,  227,  218,  228,  218,  218,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      218,  218,  218,  230,  230,  218,  231,  218,  218,  218,

      232,  232,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  218,  218,  218,  218,  218,  218,  218,  218,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  218,
      218,  218,  218,  218,  218,  218,  218,  228,  228,  228,
      228,  228,  228,  228,  228,  218,  218,  218,  218,  218,
      218,  228,  228,  228,  228,  228,  228,  218,  218,  218,
      218,  218,  228,  228,  228,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,    0,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218
    } ;

static yyconst flex_uint16_t yy_nxt[491] =
    {   0,
      218,   25,   25,   25,   25,   25,   25,   24,   25,   25,
       25,   24,   26,   27,   28,   29,   30,   31,   32,   33,
       24,   34,   24,   35,   24,   36,   37,   38,   39,   40,
       41,   34,   42,   34,   34,   34,   43,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   44,   45,   24,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   46,   25,   25,   25,  171,   25,
       25,   25,   25,   51,   51,   25,   51,   51,   97,   81,
       47,  172,   78,   48,   47,   82,  217,   48,   25,   25,
       25,   25,   25,   25,   56,   25,   56,   56,   25,   56,

       59,   59,   59,   89,   24,   90,   52,  216,  202,   52,
       57,  203,  215,   57,   59,   59,   59,  214,   24,  213,
       49,   67,   67,   67,   49,   24,   25,   25,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,  212,
       24,   24,   24,   24,   54,   25,   25,   25,  211,   60,
       25,   25,   25,   79,   60,   62,   62,   62,   62,   62,
       62,   65,   65,   65,   24,   24,   24,   63,   80,  210,
       63,   85,   86,   87,   67,   95,   95,  209,   66,   67,
       67,   67,   24,   24,   25,   25,   25,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,  208,   24,   24,

       24,   24,   54,   65,   65,   65,   70,   71,  207,   72,
       73,   99,  102,  102,  102,  206,   74,  205,   75,  204,
       66,  100,   24,   24,   24,   67,   67,   67,   67,   67,
       67,   67,   67,   67,  110,   99,  111,   67,   95,   95,
       24,  102,  102,  102,  201,  100,  200,  199,  100,  100,
      112,  198,  197,  196,  100,  100,  100,  195,  194,  193,
      111,  192,  191,  111,  111,  190,  189,  188,  187,  111,
      111,  111,  100,  100,  112,  186,  185,  184,  100,  100,
      100,  183,  182,  181,  180,  179,  178,  111,  111,  177,
      176,  175,  174,  111,  111,  111,   24,   24,   24,   24,

       24,   50,   50,   50,   50,   50,   53,   53,   53,   53,
       53,   55,   55,   55,   55,   55,   58,   58,   58,   58,
       58,   61,   61,   61,   61,   61,   64,   64,   64,   64,
       64,   68,   68,   68,   68,   68,   76,   76,   76,   76,
       76,   91,   91,  173,   91,   91,   94,  170,   94,   94,
       94,  101,  101,  101,  169,  101,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  127,  126,  125,

      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  113,   77,  109,  108,  107,  106,  105,  104,   69,
      103,   98,   96,   93,   92,   88,   84,   83,   77,   69,
      218,   23,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218
    } ;

static yyconst flex_int16_t yy_chk[491] =
    {   0,
        0,    1,    1,    1,    2,    2,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    5,    5,    5,  156,    6,
        6,    6,    7,    7,    7,    8,    8,    8,  231,   38,
        5,  156,  228,    5,    6,   38,  215,    6,    9,    9,
        9,   10,   10,   10,   13,   13,   13,   14,   14,   14,

       15,   15,   15,   43,   15,   43,    9,  214,  201,   10,
       13,  201,  213,   14,   16,   16,   16,  212,   16,  211,
        5,   25,   25,   25,    6,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,  210,
       11,   11,   11,   11,   11,   17,   17,   17,  209,   17,
       18,   18,   18,   35,   18,   19,   19,   19,   20,   20,
       20,   21,   21,   21,   11,   11,   11,   19,   35,  208,
       20,   41,   41,   41,   51,   51,   51,  207,   21,   56,
       56,   56,   11,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,  206,   12,   12,

       12,   12,   12,   22,   22,   22,   27,   27,  205,   27,
       27,   57,   59,   59,   59,  204,   27,  203,   27,  202,
       22,   57,   12,   12,   12,   62,   62,   62,   65,   65,
       65,   67,   67,   67,   79,  100,   79,   95,   95,   95,
       12,  102,  102,  102,  199,  100,  198,  196,   57,   57,
       79,  192,  191,  188,   57,   57,   57,  187,  186,  185,
      111,  181,  180,   79,   79,  178,  177,  176,  175,   79,
       79,   79,  100,  100,  111,  174,  171,  170,  100,  100,
      100,  169,  168,  167,  166,  165,  164,  111,  111,  162,
      160,  159,  158,  111,  111,  111,  219,  219,  219,  219,

      219,  220,  220,  220,  220,  220,  221,  221,  221,  221,
      221,  222,  222,  222,  222,  222,  223,  223,  223,  223,
      223,  224,  224,  224,  224,  224,  225,  225,  225,  225,
      225,  226,  226,  226,  226,  226,  227,  227,  227,  227,
      227,  229,  229,  157,  229,  229,  230,  154,  230,  230,
      230,  232,  232,  232,  153,  232,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  131,  130,  129,  128,  127,
      126,  124,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  112,  110,  109,  108,  107,  106,  105,  104,  103,

       93,   91,   90,   89,   88,   87,   86,   85,   84,   83,
       82,   81,   76,   75,   74,   73,   72,   71,   70,   68,
       63,   54,   52,   49,   48,   42,   40,   39,   28,   26,
       23,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "dtd_parse.l"

/*
 * We want a reentrant scanner.
 */
/*
 * We don't use input, so don't generate code for it.
 */
#define YY_NO_INPUT 1
/*
 * We don't use unput, so don't generate code for it.
 */
/*
 * We don't read interactively from the terminal.
 */
/*
 * We want to stop processing when we get to the end of the input.
 */
/*
 * The type for the state we keep for a scanner.
 */
/*
 * Prefix scanner routines with "Dtd_Parse_" rather than "yy", so this scanner
 * can coexist with other scanners.
 */
/*
 * We have to override the memory allocators so that we don't get
 * "unused argument" warnings from the yyscanner argument (which
 * we don't use, as we have a global memory allocator).
 *
 * We provide, as macros, our own versions of the routines generated by Flex,
 * which just call malloc()/realloc()/free() (as the Flex versions do),
 * discarding the extra argument.
 */
#line 58 "dtd_parse.l"

	/* dtd_parse.l
	* an XML dissector for Wireshark
	* lexical analyzer for DTDs
	*
	* Copyright 2004, Luis E. Garcia Ontanon <luis@ontanon.org>
	*
	* Wireshark - Network traffic analyzer
	* By Gerald Combs <gerald@wireshark.org>
	* Copyright 1998 Gerald Combs
	*
	* This program is free software; you can redistribute it and/or
	* modify it under the terms of the GNU General Public License
	* as published by the Free Software Foundation; either version 2
	* of the License, or (at your option) any later version.
	*
	* This program is distributed in the hope that it will be useful,
	* but WITHOUT ANY WARRANTY; without even the implied warranty of
	* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	* GNU General Public License for more details.
	*
	* You should have received a copy of the GNU General Public License
	* along with this program; if not, write to the Free Software
	* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
	*/

#include <glib.h>
#include <string.h>

#include "dtd.h"
#include "dtd_grammar.h"
#include "dtd_parse.h"

	struct _proto_xmlpi_attr {
		const gchar* name;
		void (*act)(gchar*);
	};

	typedef struct {
		GString* input_string;
		size_t offsetx;
		size_t len;
		void* pParser;
		gchar* location;
		gchar* attr_name;
	} Dtd_Parse_scanner_state_t;

	static size_t my_yyinput(Dtd_Parse_scanner_state_t *state,char* buff,size_t size);

	static dtd_token_data_t* new_token(gchar*,gchar*);

	static dtd_build_data_t* build_data;

	static void set_proto_name (gchar* val) { if(build_data->proto_name) g_free(build_data->proto_name); build_data->proto_name = g_strdup(val); }
	static void set_media_type (gchar* val) { if(build_data->media_type) g_free(build_data->media_type); build_data->media_type = g_strdup(val); }
	static void set_proto_root (gchar* val) { if(build_data->proto_root) g_free(build_data->proto_root); build_data->proto_root = g_strdup(val); }
	static void set_description (gchar* val) { if(build_data->description) g_free(build_data->description); build_data->description = g_strdup(val); }
	static void set_recursive (gchar* val) { build_data->recursion = ( g_ascii_strcasecmp(val,"yes") == 0 ) ? TRUE : FALSE; }

#ifdef DEBUG_DTD_PARSER
#define DEBUG_DTD_TOKEN fprintf(stderr,"->%s (%i)%s\n",location,token_type,yytext)
#else
#define DEBUG_DTD_TOKEN
#endif

#define DTD_PARSE(token_type) \
	{   DEBUG_DTD_TOKEN; \
		DtdParse(yyextra->pParser, (token_type), new_token(yytext, yyextra->location), build_data); \
		if(build_data->error->len > 0) yyterminate(); \
	}


#define YY_INPUT(buff,result,max_size) ( (result) = my_yyinput(yyextra,(buff),(max_size)) )
#define YY_USER_INIT BEGIN DTD;

/*
 * Flex (v 2.5.35) uses this symbol to "exclude" unistd.h
 */
#ifdef _WIN32
#define YY_NO_UNISTD_H
#endif

/*
 * Sleazy hack to suppress compiler warnings in yy_fatal_error().
 */
#define YY_EXIT_FAILURE ((void)yyscanner, 2)

/*
 * Macros for the allocators, to discard the extra argument.
 */
#define Dtd_Parse_alloc(size, yyscanner)	(void *)malloc(size)
#define Dtd_Parse_realloc(ptr, size, yyscanner)	(void *)realloc((char *)(ptr), (size))
#define Dtd_Parse_free(ptr, yyscanner)		free((char *)ptr)


#line 758 "dtd_parse.c"

#define INITIAL 0
#define DTD 1
#define XMLPI 2
#define LOCATION 3
#define DONE 4
#define PROTOCOL 5
#define GET_ATTR_QUOTE 6
#define GET_ATTR_VAL 7
#define GET_ATTR_CLOSE_QUOTE 8
#define IN_COMMENT 9
#define IN_NOTATION 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE Dtd_Parse_scanner_state_t *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int Dtd_Parse_lex_init (yyscan_t* scanner);

int Dtd_Parse_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int Dtd_Parse_lex_destroy (yyscan_t yyscanner );

int Dtd_Parse_get_debug (yyscan_t yyscanner );

void Dtd_Parse_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE Dtd_Parse_get_extra (yyscan_t yyscanner );

void Dtd_Parse_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *Dtd_Parse_get_in (yyscan_t yyscanner );

void Dtd_Parse_set_in  (FILE * _in_str ,yyscan_t yyscanner );

FILE *Dtd_Parse_get_out (yyscan_t yyscanner );

void Dtd_Parse_set_out  (FILE * _out_str ,yyscan_t yyscanner );

yy_size_t Dtd_Parse_get_leng (yyscan_t yyscanner );

char *Dtd_Parse_get_text (yyscan_t yyscanner );

int Dtd_Parse_get_lineno (yyscan_t yyscanner );

void Dtd_Parse_set_lineno (int _line_number ,yyscan_t yyscanner );

int Dtd_Parse_get_column  (yyscan_t yyscanner );

void Dtd_Parse_set_column (int _column_no ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int Dtd_Parse_wrap (yyscan_t yyscanner );
#else
extern int Dtd_Parse_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int Dtd_Parse_lex (yyscan_t yyscanner);

#define YY_DECL int Dtd_Parse_lex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			Dtd_Parse_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				Dtd_Parse__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		Dtd_Parse__load_buffer_state(yyscanner );
		}

	{
#line 215 "dtd_parse.l"


#line 1028 "dtd_parse.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 219 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 218 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 217 "dtd_parse.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 220 "dtd_parse.l"
{ BEGIN IN_COMMENT; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
#line 222 "dtd_parse.l"
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 222 "dtd_parse.l"
;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 223 "dtd_parse.l"
{ BEGIN DTD; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 225 "dtd_parse.l"
{ BEGIN IN_NOTATION; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 226 "dtd_parse.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 227 "dtd_parse.l"
{ BEGIN DTD; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 229 "dtd_parse.l"
{
	BEGIN XMLPI;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 233 "dtd_parse.l"
{
	BEGIN LOCATION;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 237 "dtd_parse.l"
{
	BEGIN PROTOCOL;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 241 "dtd_parse.l"
;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 242 "dtd_parse.l"
BEGIN DTD;
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 244 "dtd_parse.l"
{
	if(yyextra->location) g_free(yyextra->location);
	yyextra->location = g_strdup(yytext);
	BEGIN DONE;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 250 "dtd_parse.l"
BEGIN DTD;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 252 "dtd_parse.l"
{
	yyextra->attr_name = g_ascii_strdown(yytext, -1);
	BEGIN GET_ATTR_QUOTE;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 257 "dtd_parse.l"
{ BEGIN GET_ATTR_VAL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 259 "dtd_parse.l"
{
	g_string_append_printf(build_data->error,
					"error in wireshark:protocol xmpli at %s : could not find attribute value!",
					yyextra->location);
	yyterminate();
}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 266 "dtd_parse.l"
{
	/*"*/
	struct _proto_xmlpi_attr* pa;
	gboolean got_it = FALSE;
	static struct _proto_xmlpi_attr proto_attrs[] =
	{
		{ "proto_name", set_proto_name },
		{ "media", set_media_type },
		{ "root", set_proto_root },
		{ "description", set_description },
		{ "hierarchy", set_recursive },
		{NULL,NULL}
	};

	for(pa = proto_attrs; pa->name; pa++) {
		if (g_ascii_strcasecmp(yyextra->attr_name,pa->name) == 0) {
			pa->act(yytext);
			got_it = TRUE;
			break;
		}
	}

	if (! got_it) {
		g_string_append_printf(build_data->error,
						"error in wireshark:protocol xmpli at %s : no such parameter %s!",
						yyextra->location, yyextra->attr_name);
		g_free(yyextra->attr_name);
		yyterminate();
	}

	g_free(yyextra->attr_name);

	BEGIN GET_ATTR_CLOSE_QUOTE;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 301 "dtd_parse.l"
{ BEGIN PROTOCOL;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 303 "dtd_parse.l"
BEGIN DTD;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 305 "dtd_parse.l"
{ DTD_PARSE(TOKEN_TAG_START); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 306 "dtd_parse.l"
{ DTD_PARSE(TOKEN_TAG_STOP); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 308 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATTLIST_KW); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 309 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ELEMENT_KW); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 310 "dtd_parse.l"
{ DTD_PARSE(TOKEN_DOCTYPE_KW); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 312 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ELEM_DATA); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 313 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ELEM_DATA); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 314 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ELEM_DATA); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 315 "dtd_parse.l"
{ DTD_PARSE(TOKEN_EMPTY_KW); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 317 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_TYPE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 318 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_TYPE); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 319 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_TYPE); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 320 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_TYPE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 321 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_TYPE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 322 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_TYPE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 323 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_TYPE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 324 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_TYPE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 325 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_TYPE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 326 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_DEF_WITH_VALUE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 327 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_DEF_WITH_VALUE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 328 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_DEF); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 329 "dtd_parse.l"
{ DTD_PARSE(TOKEN_ATT_DEF); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 331 "dtd_parse.l"
{ DTD_PARSE(TOKEN_STAR); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 332 "dtd_parse.l"
{ DTD_PARSE(TOKEN_QUESTION); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 333 "dtd_parse.l"
{ DTD_PARSE(TOKEN_PLUS); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 334 "dtd_parse.l"
{ DTD_PARSE(TOKEN_COMMA); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 335 "dtd_parse.l"
{ DTD_PARSE(TOKEN_OPEN_PARENS); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 336 "dtd_parse.l"
{ DTD_PARSE(TOKEN_CLOSE_PARENS); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 337 "dtd_parse.l"
{ DTD_PARSE(TOKEN_OPEN_BRACKET); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 338 "dtd_parse.l"
{ DTD_PARSE(TOKEN_CLOSE_BRACKET); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 339 "dtd_parse.l"
{ DTD_PARSE(TOKEN_PIPE); }
	YY_BREAK
case 53:
/* rule 53 can match eol */
#line 342 "dtd_parse.l"
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 342 "dtd_parse.l"
{ DTD_PARSE(TOKEN_QUOTED); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 343 "dtd_parse.l"
{ DTD_PARSE(TOKEN_NAME); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 345 "dtd_parse.l"
ECHO;
	YY_BREAK
#line 1414 "dtd_parse.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DTD):
case YY_STATE_EOF(XMLPI):
case YY_STATE_EOF(LOCATION):
case YY_STATE_EOF(DONE):
case YY_STATE_EOF(PROTOCOL):
case YY_STATE_EOF(GET_ATTR_QUOTE):
case YY_STATE_EOF(GET_ATTR_VAL):
case YY_STATE_EOF(GET_ATTR_CLOSE_QUOTE):
case YY_STATE_EOF(IN_COMMENT):
case YY_STATE_EOF(IN_NOTATION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * Dtd_Parse_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( Dtd_Parse_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of Dtd_Parse_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	yy_size_t number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Dtd_Parse_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			Dtd_Parse_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) Dtd_Parse_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 219 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 219 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 218);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					Dtd_Parse_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( Dtd_Parse_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void Dtd_Parse_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        Dtd_Parse_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            Dtd_Parse__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	Dtd_Parse__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	Dtd_Parse__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void Dtd_Parse__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		Dtd_Parse_pop_buffer_state();
	 *		Dtd_Parse_push_buffer_state(new_buffer);
     */
	Dtd_Parse_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	Dtd_Parse__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (Dtd_Parse_wrap()) processing, but the only time this flag
	 * is looked at is after Dtd_Parse_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void Dtd_Parse__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE Dtd_Parse__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Dtd_Parse_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Dtd_Parse__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) Dtd_Parse_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in Dtd_Parse__create_buffer()" );

	b->yy_is_our_buffer = 1;

	Dtd_Parse__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with Dtd_Parse__create_buffer()
 * @param yyscanner The scanner object.
 */
    void Dtd_Parse__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		Dtd_Parse_free((void *) b->yy_ch_buf ,yyscanner );

	Dtd_Parse_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a Dtd_Parse_restart() or at EOF.
 */
    static void Dtd_Parse__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	Dtd_Parse__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then Dtd_Parse__init_buffer was _probably_
     * called from Dtd_Parse_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void Dtd_Parse__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		Dtd_Parse__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void Dtd_Parse_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	Dtd_Parse_ensure_buffer_stack(yyscanner);

	/* This block is copied from Dtd_Parse__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from Dtd_Parse__switch_to_buffer. */
	Dtd_Parse__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void Dtd_Parse_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	Dtd_Parse__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		Dtd_Parse__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void Dtd_Parse_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)Dtd_Parse_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in Dtd_Parse_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)Dtd_Parse_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in Dtd_Parse_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE Dtd_Parse__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) Dtd_Parse_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Dtd_Parse__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	Dtd_Parse__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to Dtd_Parse_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       Dtd_Parse__scan_bytes() instead.
 */
YY_BUFFER_STATE Dtd_Parse__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return Dtd_Parse__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to Dtd_Parse_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Dtd_Parse__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) Dtd_Parse_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in Dtd_Parse__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = Dtd_Parse__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in Dtd_Parse__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE Dtd_Parse_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int Dtd_Parse_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int Dtd_Parse_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *Dtd_Parse_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *Dtd_Parse_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t Dtd_Parse_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *Dtd_Parse_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void Dtd_Parse_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void Dtd_Parse_set_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "Dtd_Parse_set_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void Dtd_Parse_set_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "Dtd_Parse_set_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see Dtd_Parse__switch_to_buffer
 */
void Dtd_Parse_set_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void Dtd_Parse_set_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int Dtd_Parse_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void Dtd_Parse_set_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* Dtd_Parse_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int Dtd_Parse_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) Dtd_Parse_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* Dtd_Parse_lex_init_extra has the same functionality as Dtd_Parse_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to Dtd_Parse_alloc in
 * the yyextra field.
 */

int Dtd_Parse_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    Dtd_Parse_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) Dtd_Parse_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    Dtd_Parse_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from Dtd_Parse_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * Dtd_Parse_lex_init()
     */
    return 0;
}

/* Dtd_Parse_lex_destroy is for both reentrant and non-reentrant scanners. */
int Dtd_Parse_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		Dtd_Parse__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		Dtd_Parse_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	Dtd_Parse_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        Dtd_Parse_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * Dtd_Parse_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    Dtd_Parse_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#line 345 "dtd_parse.l"



static dtd_token_data_t* new_token(gchar* text, gchar* location) {
	dtd_token_data_t* t = g_new(dtd_token_data_t,1);

	t->text = g_strdup(text);
	t->location = g_strdup(location);

	return t;
}


static size_t my_yyinput(Dtd_Parse_scanner_state_t *state, char* buff, size_t size) {

	if (state->offsetx >= state->len) {
		return YY_NULL;
	} else if (state->offsetx + size <= state->len) {
		memcpy(buff, state->input_string->str + state->offsetx, size);
		state->offsetx += size;
		return size;
	} else {
		size = state->len - state->offsetx;
		memcpy(buff, state->input_string->str + state->offsetx, size);
		state->offsetx = state->len;
		return size;
	}
}

extern dtd_build_data_t* dtd_parse(GString* s) {
	yyscan_t scanner;
	Dtd_Parse_scanner_state_t state;

	if (Dtd_Parse_lex_init(&scanner) != 0) {
#ifdef DEBUG_DTD_PARSER
		fprintf(stderr, "Can't initialize scanner: %s\n",
		    strerror(errno));
#endif
		return NULL;
	}

	state.input_string = s;
	state.offsetx = 0;
	state.len = state.input_string->len;

	state.pParser = DtdParseAlloc(g_malloc);

#ifdef DEBUG_DTD_PARSER
	DtdParseTrace(stderr, ">>");
#endif

	build_data = g_new(dtd_build_data_t,1);

	build_data->proto_name = NULL;
	build_data->media_type = NULL;
	build_data->description = NULL;
	build_data->proto_root = NULL;
	build_data->recursion = FALSE;

	build_data->elements = g_ptr_array_new();
	build_data->attributes = g_ptr_array_new();

	build_data->error = g_string_new("");

	state.location = NULL;
	state.attr_name = NULL;

	/* Associate the state with the scanner */
	Dtd_Parse_set_extra(&state, scanner);

	Dtd_Parse_lex(scanner);

	DtdParse(state.pParser, 0, NULL, build_data);

	Dtd_Parse_lex_destroy(scanner);

	if (state.location)
		g_free(state.location);

	DtdParseFree(state.pParser, g_free);

	return build_data;
}

