all: flash_patch_extractor ucode_extractor

flash_patch_extractor: FORCE
	@printf "\033[0;31m  BUILDING\033[0m %s\n" $@
	$(Q)make -C $@

ucode_extractor: FORCE
	@printf "\033[0;31m  BUILDING\033[0m %s\n" $@
	$(Q)make -C $@

FORCE:
	