#!/usr/bin/env bash
#
# Build a native linux-aarch64 toolchain view for an Android NDK.
#
# Google ships no linux-aarch64 NDK: build/tools/ndk_bin_common.sh maps
# Linux/aarch64 straight to x86_64, so on an ARM64 host every clang invocation
# is emulated by qemu-x86_64. That is roughly an order of magnitude slower and
# occasionally aborts mid-compile ("libc++abi: Pure virtual function called!",
# "qemu: uncaught target signal 6"), which shows up as a random build failure.
#
# This creates $NDK/toolchains/llvm/prebuilt/linux-aarch64 as a symlink farm:
# native LLVM host binaries where the distro provides them, falling back to the
# x86_64 originals (still via qemu) for anything it does not. Everything else --
# sysroot, target runtime libraries, headers -- is shared with the x86_64 tree,
# so no NDK file is modified and removing the directory fully reverts this.
#
# Point ndk-build at it by exporting HOST_ARCH=aarch64 (see init.mk: HOST_TAG64
# is derived from HOST_ARCH, and TOOLCHAIN_ROOT from HOST_TAG64).
#
# Usage: ndk-native-aarch64.sh [NDK_ROOT] [LLVM_PREFIX]

set -euo pipefail

NDK="${1:-${NDK_ROOT:-${ANDROID_NDK_ROOT:-}}}"
if [ -z "$NDK" ] && [ -d /opt/android-sdk/ndk ]; then
    NDK=$(find /opt/android-sdk/ndk -mindepth 1 -maxdepth 1 -type d | sort -V | tail -n 1)
fi
[ -n "$NDK" ] && [ -d "$NDK" ] || { echo "ERROR: set NDK_ROOT or pass the NDK path" >&2; exit 1; }

SRC="$NDK/toolchains/llvm/prebuilt/linux-x86_64"
DST="$NDK/toolchains/llvm/prebuilt/linux-aarch64"
[ -d "$SRC" ] || { echo "ERROR: $SRC not found" >&2; exit 1; }

# The NDK's clang major version decides which host LLVM can stand in for it:
# the resource directory it picks up is $DST/lib/clang/<major>, shared with the
# x86_64 tree, so a mismatched host clang would read the wrong builtin headers.
NDK_CLANG_MAJOR=$(basename "$(ls -d "$SRC"/lib/clang/* | sort -V | tail -n 1)")

LLVM="${2:-}"
if [ -z "$LLVM" ]; then
    for p in "/usr/lib/llvm-$NDK_CLANG_MAJOR"; do
        [ -x "$p/bin/clang" ] && LLVM="$p" && break
    done
fi
if [ -z "$LLVM" ] || [ ! -x "$LLVM/bin/clang" ]; then
    echo "ERROR: no native clang $NDK_CLANG_MAJOR found (expected /usr/lib/llvm-$NDK_CLANG_MAJOR)." >&2
    echo "       Install it, e.g.: apt-get install clang-$NDK_CLANG_MAJOR lld-$NDK_CLANG_MAJOR" >&2
    exit 1
fi
[ -d "$LLVM/lib/clang/$NDK_CLANG_MAJOR" ] || {
    echo "ERROR: $LLVM is not clang $NDK_CLANG_MAJOR" >&2; exit 1; }

echo "NDK        : $NDK"
echo "host LLVM  : $LLVM (clang $NDK_CLANG_MAJOR)"
echo "creating   : $DST"

rm -rf "$DST"
mkdir -p "$DST/bin"

# Share everything that is host-independent (sysroot, target runtimes, headers).
for entry in "$SRC"/*; do
    name=$(basename "$entry")
    [ "$name" = bin ] && continue
    ln -s "$entry" "$DST/$name"
done

# A distro host clang standing in for the NDK's clang has two Android-hostile
# defaults: it links libgcc (which NDK r23+ no longer ships, so ld.lld fails
# with "unable to find library -lgcc"), and it resolves its resource directory
# next to the real binary (the distro LLVM tree), where the Android runtime
# libraries are absent. Wrap it so it picks up the NDK's shared resource dir --
# $DST/lib is a symlink to the x86_64 tree, which carries the per-arch
# compiler-rt builtins and libunwind -- and selects the compiler-rt/libunwind
# runtime the NDK actually provides. Frontend (-cc1) calls are passed through
# untouched. The per-API drivers and ndk-build both link through "$bin_dir/clang".
write_clang_wrapper() {
    dst="$1"; real="$2"
    cat > "$dst" <<EOF
#!/usr/bin/env bash
# Generated by ndk-native-aarch64.sh -- do not edit.
real="$real"
bin_dir=\$(cd "\$(dirname "\$0")" && pwd)
if [ "\$1" = "-cc1" ]; then
    exec "\$real" "\$@"
fi
# --sysroot: the link step passes none and the distro clang would default it
# next to its own binary, missing the NDK sysroot's crt objects and libc; any
# --sysroot ndk-build does pass (compile) comes later in "\$@" and still wins.
exec "\$real" --sysroot "\$bin_dir/../sysroot" \\
    -resource-dir "\$bin_dir/../lib/clang/$NDK_CLANG_MAJOR" \\
    --rtlib=compiler-rt --unwindlib=libunwind \\
    -Wno-unused-command-line-argument "\$@"
EOF
    chmod +x "$dst"
}

native=0
emulated=0
for entry in "$SRC"/bin/*; do
    name=$(basename "$entry")
    # clang / clang++ need the Android-runtime wrapper described above rather
    # than a bare symlink to the distro binary.
    case "$name" in
    clang|clang++)
        if [ -x "$LLVM/bin/$name" ]; then
            write_clang_wrapper "$DST/bin/$name" "$LLVM/bin/$name"
            native=$((native + 1))
            continue
        fi
        ;;
    esac
    # The per-API triple drivers are arch-independent bash wrappers that re-exec
    # "$(dirname $0)/clang"; copy them so they pick up the native clang here.
    if head -c 2 "$entry" 2>/dev/null | grep -q '#!'; then
        cp "$entry" "$DST/bin/$name"
        continue
    fi
    # Some entries are symlinks within bin (ld -> lld); match on what they
    # resolve to so those pick up the native tool as well.
    target=$name
    if [ -L "$entry" ]; then
        target=$(basename "$(readlink "$entry")")
    fi
    if [ -x "$LLVM/bin/$name" ]; then
        ln -s "$LLVM/bin/$name" "$DST/bin/$name"
        native=$((native + 1))
    elif [ -x "$LLVM/bin/$target" ]; then
        ln -s "$LLVM/bin/$target" "$DST/bin/$name"
        native=$((native + 1))
    else
        # No native counterpart (e.g. yasm, an x86-only assembler): keep the
        # x86_64 binary, which binfmt_misc still runs under qemu.
        ln -s "$entry" "$DST/bin/$name"
        emulated=$((emulated + 1))
    fi
done

echo "binaries   : $native native, $emulated left emulated"

# ndk-build looks for its own make at $NDK/prebuilt/$HOST_TAG/bin/make and falls
# back to the system one; give it a native tree so it stops emulating make too.
if [ -d "$NDK/prebuilt/linux-x86_64" ]; then
    rm -rf "$NDK/prebuilt/linux-aarch64"
    mkdir -p "$NDK/prebuilt/linux-aarch64/bin"
    for entry in "$NDK/prebuilt/linux-x86_64"/*; do
        name=$(basename "$entry")
        [ "$name" = bin ] && continue
        ln -s "$entry" "$NDK/prebuilt/linux-aarch64/$name"
    done
    for entry in "$NDK/prebuilt/linux-x86_64"/bin/*; do
        name=$(basename "$entry")
        if [ "$name" = make ] && command -v make >/dev/null 2>&1; then
            ln -s "$(command -v make)" "$NDK/prebuilt/linux-aarch64/bin/make"
        else
            ln -s "$entry" "$NDK/prebuilt/linux-aarch64/bin/$name"
        fi
    done
fi

"$DST/bin/clang" --version | head -2
echo "done. Build with HOST_ARCH=aarch64 exported."
