set ::msgcat::header "Project-Id-Version: hello-tcl 0\nReport-Msgid-Bugs-To: bug-gnu-gettext@gnu.org\nPO-Revision-Date: 2003-10-20 10:13+0200\nLast-Translator: Bruno Haible <bruno@clisp.org>\nLanguage-Team: Polish <pl@li.org>\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nPlural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
::msgcat::mcset pl "Written by Fran\u00e7ois Pinard." "Program napisa\u0142 Fran\u00e7ois Pinard."
::msgcat::mcset pl "error %1." "b\u0142\u0105d %1."
