LOCAL_PATH:= $(call my-dir)
WIRESHARK_SRC_PATH:= $(LOCAL_PATH)/../wireshark

include $(CLEAR_VARS)
LOCAL_SRC_FILES := \
	$(WIRESHARK_SRC_PATH)/epan/addr_and_mask.c \
	$(WIRESHARK_SRC_PATH)/epan/addr_resolv.c \
	$(WIRESHARK_SRC_PATH)/epan/address_types.c \
	$(WIRESHARK_SRC_PATH)/epan/afn.c \
	$(WIRESHARK_SRC_PATH)/epan/aftypes.c \
	$(WIRESHARK_SRC_PATH)/epan/app_mem_usage.c \
	$(WIRESHARK_SRC_PATH)/epan/asn1.c \
	$(WIRESHARK_SRC_PATH)/epan/capture_dissectors.c \
	$(WIRESHARK_SRC_PATH)/epan/charsets.c \
	$(WIRESHARK_SRC_PATH)/epan/circuit.c \
	$(WIRESHARK_SRC_PATH)/epan/color_filters.c \
	$(WIRESHARK_SRC_PATH)/epan/column.c \
	$(WIRESHARK_SRC_PATH)/epan/column-utils.c \
	$(WIRESHARK_SRC_PATH)/epan/conversation.c \
	$(WIRESHARK_SRC_PATH)/epan/conversation_table.c \
	$(WIRESHARK_SRC_PATH)/epan/crc10-tvb.c \
	$(WIRESHARK_SRC_PATH)/epan/crc16-tvb.c \
	$(WIRESHARK_SRC_PATH)/epan/crc32-tvb.c \
	$(WIRESHARK_SRC_PATH)/epan/crc6-tvb.c \
	$(WIRESHARK_SRC_PATH)/epan/crc8-tvb.c \
	$(WIRESHARK_SRC_PATH)/epan/decode_as.c \
	$(WIRESHARK_SRC_PATH)/epan/disabled_protos.c \
	$(WIRESHARK_SRC_PATH)/epan/dissector_filters.c \
	$(WIRESHARK_SRC_PATH)/epan/dvb_chartbl.c \
	$(WIRESHARK_SRC_PATH)/epan/dwarf.c \
	$(WIRESHARK_SRC_PATH)/epan/epan.c \
	$(WIRESHARK_SRC_PATH)/epan/ex-opt.c \
	$(WIRESHARK_SRC_PATH)/epan/except.c \
	$(WIRESHARK_SRC_PATH)/epan/expert.c \
	$(WIRESHARK_SRC_PATH)/epan/exported_pdu.c \
	$(WIRESHARK_SRC_PATH)/epan/plugin_if.c \
	$(WIRESHARK_SRC_PATH)/epan/filter_expressions.c \
	$(WIRESHARK_SRC_PATH)/epan/follow.c \
	$(WIRESHARK_SRC_PATH)/epan/frame_data.c \
	$(WIRESHARK_SRC_PATH)/epan/frame_data_sequence.c \
	$(WIRESHARK_SRC_PATH)/epan/funnel.c \
	$(WIRESHARK_SRC_PATH)/epan/g_int64_hash_routines.c \
	$(WIRESHARK_SRC_PATH)/epan/geoip_db.c \
	$(WIRESHARK_SRC_PATH)/epan/golay.c \
	$(WIRESHARK_SRC_PATH)/epan/guid-utils.c \
	$(WIRESHARK_SRC_PATH)/epan/iana_charsets.c \
	$(WIRESHARK_SRC_PATH)/epan/in_cksum.c \
	$(WIRESHARK_SRC_PATH)/epan/ipproto.c \
	$(WIRESHARK_SRC_PATH)/epan/ipv4.c \
	$(WIRESHARK_SRC_PATH)/epan/media_params.c \
	$(WIRESHARK_SRC_PATH)/epan/next_tvb.c \
	$(WIRESHARK_SRC_PATH)/epan/oids.c \
	$(WIRESHARK_SRC_PATH)/epan/osi-utils.c \
	$(WIRESHARK_SRC_PATH)/epan/oui.c \
	$(WIRESHARK_SRC_PATH)/epan/packet-range.c \
	$(WIRESHARK_SRC_PATH)/epan/packet.c \
	$(WIRESHARK_SRC_PATH)/epan/prefs.c \
	$(WIRESHARK_SRC_PATH)/epan/print.c \
	$(WIRESHARK_SRC_PATH)/epan/print_stream.c \
	$(WIRESHARK_SRC_PATH)/epan/proto.c \
	$(WIRESHARK_SRC_PATH)/epan/proto_data.c \
	$(WIRESHARK_SRC_PATH)/epan/range.c \
	$(WIRESHARK_SRC_PATH)/epan/reassemble.c \
	$(WIRESHARK_SRC_PATH)/epan/reedsolomon.c \
	$(WIRESHARK_SRC_PATH)/epan/req_resp_hdrs.c \
	$(WIRESHARK_SRC_PATH)/epan/rtd_table.c \
	$(WIRESHARK_SRC_PATH)/epan/show_exception.c \
	$(WIRESHARK_SRC_PATH)/epan/sminmpec.c \
	$(WIRESHARK_SRC_PATH)/epan/srt_table.c \
	$(WIRESHARK_SRC_PATH)/epan/stat_tap_ui.c \
	$(WIRESHARK_SRC_PATH)/epan/stats_tree.c \
	$(WIRESHARK_SRC_PATH)/epan/strutil.c \
	$(WIRESHARK_SRC_PATH)/epan/stream.c \
	$(WIRESHARK_SRC_PATH)/epan/t35.c \
	$(WIRESHARK_SRC_PATH)/epan/tap.c \
	$(WIRESHARK_SRC_PATH)/epan/timestamp.c \
	$(WIRESHARK_SRC_PATH)/epan/timestats.c \
	$(WIRESHARK_SRC_PATH)/epan/tfs.c \
	$(WIRESHARK_SRC_PATH)/epan/to_str.c \
	$(WIRESHARK_SRC_PATH)/epan/tvbparse.c \
	$(WIRESHARK_SRC_PATH)/epan/tvbuff_base64.c \
	$(WIRESHARK_SRC_PATH)/epan/tvbuff_composite.c \
	$(WIRESHARK_SRC_PATH)/epan/tvbuff_real.c \
	$(WIRESHARK_SRC_PATH)/epan/tvbuff_subset.c \
	$(WIRESHARK_SRC_PATH)/epan/tvbuff_zlib.c \
	$(WIRESHARK_SRC_PATH)/epan/tvbuff.c \
	$(WIRESHARK_SRC_PATH)/epan/uat.c \
	$(WIRESHARK_SRC_PATH)/epan/value_string.c \
	$(WIRESHARK_SRC_PATH)/epan/xdlc.c \
	$(WIRESHARK_SRC_PATH)/epan/ws_version_info.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_allocator_block.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_allocator_block_fast.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_allocator_simple.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_allocator_strict.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_array.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_core.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_interval_tree.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_list.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_map.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_miscutl.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_scopes.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_stack.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_strbuf.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_strutl.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_tree.c \
	$(WIRESHARK_SRC_PATH)/epan/wmem/wmem_user_cb.c \
	$(WIRESHARK_SRC_PATH)/epan/diam_dict.c \
	$(WIRESHARK_SRC_PATH)/epan/dtd_grammar.c \
	$(WIRESHARK_SRC_PATH)/epan/dtd_parse.c \
	$(WIRESHARK_SRC_PATH)/epan/dtd_preparse.c \
	$(WIRESHARK_SRC_PATH)/epan/ps.c \
	$(WIRESHARK_SRC_PATH)/epan/radius_dict.c \
	$(WIRESHARK_SRC_PATH)/epan/uat_load.c \
	$(WIRESHARK_SRC_PATH)/epan/asm_utils.c \
	$(WIRESHARK_SRC_PATH)/epan/crypt/airpdcap.c \
	$(WIRESHARK_SRC_PATH)/epan/crypt/airpdcap_ccmp.c \
	$(WIRESHARK_SRC_PATH)/epan/crypt/airpdcap_rijndael.c \
	$(WIRESHARK_SRC_PATH)/epan/crypt/airpdcap_tkip.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-bytes.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-double.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-guid.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-ieee-11073-float.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-integer.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-ipv4.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-ipv6.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-none.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-pcre.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-protocol.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-string.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftype-time.c \
	$(WIRESHARK_SRC_PATH)/epan/ftypes/ftypes.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/dfilter-macro.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/dfilter.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/dfunctions.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/dfvm.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/drange.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/gencode.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/grammar.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/scanner.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/semcheck.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/sttype-function.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/sttype-integer.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/sttype-pointer.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/sttype-range.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/sttype-set.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/sttype-string.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/sttype-test.c \
	$(WIRESHARK_SRC_PATH)/epan/dfilter/syntax-tree.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cosnaming.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gias.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-parlay.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tango.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/file-btsnoop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/file-elf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/file-file.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/file-gif.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/file-jpeg.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/file-mp4.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/file-pcap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/file-pcapng.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/file-png.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-2dparityfec.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-3com-njack.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-3com-xns.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-3g-a11.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-6lowpan.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-9p.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-HI2Operations.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-a21.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aarp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aastra-aasp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-acap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-acn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-acp133.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-acr122.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-acse.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-actrace.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-adb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-adb_cs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-adb_service.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-adwin-config.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-adwin.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aeron.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-afp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-afs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-agentx.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-admin.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-adverts.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-bos.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-buddylist.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-chat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-chatnav.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-directory.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-email.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-generic.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-icq.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-invitation.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-location.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-messaging.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-oft.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-popup.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-signon.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-ssi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-sst.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-stats.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-translate.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim-userlookup.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aim.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ajp13.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-alcap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-alljoyn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-amqp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-amr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ancp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ans.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ansi_637.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ansi_683.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ansi_801.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ansi_a.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ansi_map.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ansi_tcap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aodv.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aoe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aol.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ap1394.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-app-pkix-cert.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-applemidi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aprs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ar_drone.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-arcnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-armagetronad.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-arp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-artnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aruba-adp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aruba-erm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aruba-iap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-aruba-papi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-asap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ascend.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-asf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-assa_r3.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-asterix.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-at.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-atalk.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ath.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-atm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-atmtcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-atn-cm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-atn-cpdlc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-atn-ulcs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-auto_rp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ax25-kiss.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ax25-nol3.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ax25.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ax4000.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ayiya.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-babel.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bacapp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bacnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-banana.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-batadv.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bctp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-beep.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bencode.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ber.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bfcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bfd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bgp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bitcoin.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bittorrent.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bjnp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bluecom.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bluetooth.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bmc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bofl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bootp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bootparams.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bpdu.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bpq.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-brdwlk.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-brp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bssap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bssgp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bt-dht.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bt-utp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bt3ds.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btamp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btatt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btavctp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btavdtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btavrcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btbnep.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btbredr_rf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bthci_acl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bthci_cmd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bthci_evt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bthci_sco.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bthci_vendor.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bthcrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bthfp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bthid.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bthsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btl2cap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btle.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btle_rf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btmcap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btrfcomm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btsap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btsdp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-btsmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bvlc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-bzr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-c1222.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-c15ch.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-calcappprotocol.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-camel.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-canopen.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-capwap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-carp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cast.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-catapult-dct2000.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cattp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cbor.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ccsds.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cdp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cdt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cell_broadcast.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ceph.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cfdp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cfm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cgmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-chargen.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-charging_ase.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-chdlc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cigi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cimd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cimetrics.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cipmotion.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cipsafety.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cisco-erspan.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cisco-fp-mim.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cisco-marker.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cisco-metadata.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cisco-oui.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cisco-sm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cisco-ttag.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cisco-wids.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-classicstun.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-clearcase.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-clip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-clique-rm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-clnp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cmip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cmpp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cms.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cnip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-coap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-collectd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-componentstatus.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cops.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-corosync-totemnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-corosync-totemsrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-coseventcomm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cosine.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-couchbase.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cp2179.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cpfi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cpha.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cql.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-credssp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-crmf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-csm-encaps.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-csn1.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ctdb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-cups.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-daap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-data.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-daytime.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-db-lsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dbus.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dccp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-atsvc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-bossvr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-browser.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-budb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-butc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-cds_clerkserver.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-cds_solicit.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-conv.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-cprpc_server.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-dce122.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-dfs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-dnsserver.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-drsuapi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-dssetup.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-dtsprovider.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-dtsstime_req.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-efs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-epm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-eventlog.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-fileexp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-fldb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-frsapi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-frsrpc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-frstrans.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-ftserver.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-icl_rpc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-initshutdown.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-krb5rpc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-llb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-lsa.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-mapi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-mdssvc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-messenger.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-mgmt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-misc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-ndr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-netlogon.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-nspi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-nt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-pnp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rdaclif.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rep_proc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rfr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-roverride.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rpriv.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rras.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_acct.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_attr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_attr_schema.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_bind.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_misc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_pgo.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_plcy.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_prop_acct.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_prop_acl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_prop_attr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_prop_pgo.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_prop_plcy.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_pwd_mgmt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_repadm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_replist.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_repmgr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rs_unix.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-rsec_login.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-samr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-secidmap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-spoolss.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-srvsvc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-svcctl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-tapi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-tkn4int.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-trksvr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-ubikdisk.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-ubikvote.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-update.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-winreg.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-witness.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-wkssvc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc-wzcsvc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcerpc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcom-dispatch.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcom-oxid.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcom-remact.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcom-remunkn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcom-sysact.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcom.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dcp-etsi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ddtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dec-bpdu.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dec-dnart.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dect.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-devicenet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dhcp-failover.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dhcpv6.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-diameter.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-diameter_3gpp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-diffserv-mpls-common.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dis.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-disp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-distcc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dji-uav.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dlm3.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dlsw.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dmx.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dnp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dns.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dof.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dplay.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dpnss-link.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dpnss.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-drda.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dsi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dsr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dtcp-ip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dtls.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dtn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dtpt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dua.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-ait.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-bat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-data-mpe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-eit.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-ipdc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-nit.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-s2-bb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-sdt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-tdt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvb-tot.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvbci.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-dvmrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-e100.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-e164.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-e212.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-eap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-eapol.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-echo.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ecmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ecp-oui.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ecp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-edonkey.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-egd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ehdlc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ehs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-eigrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-eiss.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-elasticsearch.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-elcom.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-elmi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-enc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-enip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-enrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-enttec.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-epl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-epl_v1.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-epmd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-epon.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-erf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-erldp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-esio.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-esis.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ess.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-etag.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-etch.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-eth.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-etherip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ethertype.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-etsi_card_app_toolkit.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-etv.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-evrc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-exec.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-exported_pdu.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-extreme.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcct.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcdns.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcels.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcfcs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcfzs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcgi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fclctl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcoe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcoib.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcsb3.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fcswils.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fddi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fefd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ff.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-finger.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fix.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-flexnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-flexray.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-flip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fmp_notify.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fmtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-force10-oui.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-forces.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-foundry.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fp_hint.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fractalgeneratorprotocol.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-frame.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ftam.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ftp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-fw1.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-g723.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gadu-gadu.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gdb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gdsdb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gearman.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ged125.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-geneve.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gfp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gift.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-giop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-git.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-glbp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gluster_cli.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gluster_pmap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-glusterd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-glusterfs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-glusterfs_hndsk.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gmhdr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gmr1_bcch.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gmr1_common.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gmr1_dtap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gmr1_rach.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gmr1_rr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gmrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gnutella.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-goose.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gopher.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gpef.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gprs-llc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gprscdr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gre.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_a_bssmap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_a_common.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_a_dtap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_a_gm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_a_rp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_a_rr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_abis_om2000.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_abis_oml.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_bsslap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_bssmap_le.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_cbch.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_ipa.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_map.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_rlcmac.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_sim.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_sms.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_sms_ud.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsm_um.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gsmtap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gssapi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gtpv2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gvcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gvrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-gvsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h1.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h221_nonstd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h223.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h225.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h235.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h245.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h248.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h248_10.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h248_2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h248_3gpp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h248_7.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h248_annex_c.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h248_annex_e.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h248_q1950.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h261.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h263.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h263p.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h264.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h282.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h283.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h323.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h450-ros.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h450.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h460.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-h501.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hartip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hazelcast.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hci_h1.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hci_h4.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hci_mon.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hci_usb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hclnfsd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hcrt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hdcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hdcp2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hdfs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hdfsdata.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hdmi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hiqnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hislip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hnbap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-homeplug-av.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-homeplug.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hp-erm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hpext.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hpfeeds.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hpsw.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hpteam.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hsr-prp-supervision.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hsr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hsrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-http-urlencoded.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-http.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-http2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-hyperscsi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-i2c.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iana-oui.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iapp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iax2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-icap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-icep.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-icmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-icmpv6.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-icp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-icq.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-idmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-idp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-idrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iec104.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee1722.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee17221.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee80211-netmon.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee80211-prism.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee80211-radio.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee80211-radiotap-iter.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee80211-radiotap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee80211-wlancap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee80211.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee802154.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee8021ah.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee8023.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ieee802a.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ifcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-igap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-igmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-igrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ilp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-imap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-imf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-inap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-infiniband.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-infiniband_sdp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-interlink.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipars.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipdc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipdr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipfc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-app.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-bridge.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-chassis.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-picmg.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-pps.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-se.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-session.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-storage.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-trace.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-transport.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-update.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi-vita.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipmi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipoib.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipos.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipsec-tcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipsec-udp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipsec.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipsi-ctl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipv6.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipvs-syncd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipx.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ipxwan.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-irc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isakmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iscsi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isdn-sup.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isdn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iser.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isis-clv.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isis-hello.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isis-lsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isis-snp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isis.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ismacryp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ismp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isns.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iso14443.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iso7816.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iso8583.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-isup.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-itdm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iua.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iuup.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iwarp-ddp-rdmap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-iwarp-mpa.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ixiatrailer.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ixveriwave.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-j1939.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-jmirror.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-jpeg.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-json.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-juniper.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-jxta.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-k12.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kadm5.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kafka.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kdp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kdsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kerberos.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kerberos4.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kingfisher.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kink.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kismet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-klm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-knet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-knxnetip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kpasswd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-kt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-l1-events.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-l2tp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lacp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lanforge.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lapb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lapbether.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lapd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lapdm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-laplink.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lapsat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lbm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lbmc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lbmpdm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lbmpdmtcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lbmr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lbtrm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lbtru.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lbttcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lcsap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ldap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ldp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ldss.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lg8979.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lge_monitor.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-link16.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-linx.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lisp-data.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lisp-tcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lisp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-llc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lldp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-llrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-llt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lltd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lmi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-logcat-text.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-logcat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-logotypecertextn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lon.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-loop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lpd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lpp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lppa.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lppe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lsc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lte-rrc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ltp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lwapp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lwm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lwm2mtlv.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-lwres.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-m2pa.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-m2tp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-m2ua.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-m3ap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-m3ua.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-maap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mac-lte-framed.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mac-lte.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-maccontrol.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-macsec.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mactelnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-manolito.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-marker.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mausb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mbim.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mbtcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mcpe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mdshdr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-media.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-megaco.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-memcache.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mesh.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-meta.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-metamako.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mgcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mih.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mikey.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mime-encap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mint.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-miop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mip6.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mka.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mms.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mmse.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mndp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mojito.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-moldudp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-moldudp64.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mongo.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mount.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mp2t.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mp4ves.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpeg-audio.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpeg-ca.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpeg-descriptor.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpeg-dsmcc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpeg-pat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpeg-pes.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpeg-pmt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpeg-sect.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpeg1.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpls-echo.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpls-pm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpls-psc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpls-y1711.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mpls.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mplstp-oam.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mq-base.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mq-pcf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mq.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mqtt-sn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mqtt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mrcpv2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mrdisc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mrp-mmrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mrp-msrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mrp-mvrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ms-mms.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-msdp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-msn-messenger.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-msnip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-msnlb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-msproxy.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-msrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mstp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mswsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mtp2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mtp3.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mtp3mg.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-multipart.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mux27010.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-mysql.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nas_eps.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nasdaq-itch.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nasdaq-soup.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nat-pmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nb_rtpmux.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nbap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nbd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nbifom.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nbipx.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nbt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ncp-nmas.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ncp-sss.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ncp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ncp2222.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ncs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ndmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ndp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ndps.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-negoex.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netanalyzer.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netbios.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netdump.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netflow.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netlink-netfilter.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netlink-route.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netlink-sock_diag.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netlink.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netperfmeter.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netrom.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-netsync.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nettl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-newmail.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nflog.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nfs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nfsacl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nfsauth.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nhrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nisplus.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nlm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nlsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nntp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-noe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-novell_pkis.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ns_cert_exts.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nsh.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nsip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nsrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nstrace.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nt-oui.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nt-tpcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ntlmssp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ntp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-null.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nwmtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-nwp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-oampdu.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-obex.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ocfs2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ocsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-oicq.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-oipf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-olsr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-omapi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-omron-fins.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-opa-fe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-opa-mad.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-opa-snc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-opa.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-openflow.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-openflow_v1.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-openflow_v4.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-openflow_v5.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-opensafety.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-openvpn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-openwire.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-opsi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-optommp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-osc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-osi-options.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-osi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ositp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ospf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ossp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ouch.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-p1.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-p22.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-p7.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-p772.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-p_mul.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-packetbb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-packetlogger.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pagp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-paltalk.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pana.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pathport.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pcap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pcap_pktdata.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pcapng_block.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pcep.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pcli.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pcnfsd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pdc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pdcp-lte.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-peekremote.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-per.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pflog.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pgm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pgsql.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pim.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pingpongprotocol.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pkcs1.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pkcs12.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pkinit.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pkix1explicit.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pkix1implicit.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pkixac.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pkixproxy.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pkixqualified.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pkixtsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pktap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pktc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pktgen.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pmproxy.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pnrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-portmap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ppcap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ppi-antenna.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ppi-geolocation-common.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ppi-gps.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ppi-sensor.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ppi-vector.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ppi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ppp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pppoe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pptp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pres.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-prp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ptp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ptpip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pulse.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pvfs2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pw-atm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pw-cesopsn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pw-common.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pw-eth.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pw-fr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pw-hdlc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pw-oam.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-pw-satop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-q2931.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-q708.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-q931.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-q932-ros.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-q932.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-q933.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-qllc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-qnet6.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-qsig.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-quake.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-quake2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-quake3.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-quakeworld.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-quic.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-radius.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-radius_packetcable.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-raknet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ranap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-raw.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rdm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rdp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rdt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-redback.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-redbackli.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-reload-framing.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-reload.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-retix-bpdu.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rfc2190.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rfid-felica.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rfid-mifare.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rfid-pn532-hci.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rfid-pn532.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rgmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-riemann.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ripng.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rlc-lte.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rlc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rlm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rlogin.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rmcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rmi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rmt-alc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rmt-fec.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rmt-lct.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rmt-norm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rnsap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rohc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-roofnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ros.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rpc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rpcap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rpcrdma.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rpki-rtr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rpl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rquota.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rrc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rrlp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rsh.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rsip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rsl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rstat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rsvd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rsvp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rsync.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtacser.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtcdc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtitcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtls.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtmpt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtp-events.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtp-midi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtpproxy.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtps.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtse.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rtsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rua.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rudp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rwall.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-rx.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-s1ap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-s5066dts.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-s5066sis.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-s7comm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-s7comm_szl_ids.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sabp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sadmind.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sametime.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sasp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sbc-ap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sbc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sbus.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sccp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sccpmg.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-scop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-scriptingservice.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-scsi-mmc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-scsi-osd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-scsi-sbc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-scsi-smc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-scsi-ssc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-scsi.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sctp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sdh.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sdlc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sdp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sebek.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-selfm.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sercosiii.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ses.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sflow.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sgsap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-shim6.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sigcomp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-simple.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-simulcrypt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sipfrag.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sita.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-skinny.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-skype.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-slimp3.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sll.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-slowprotocols.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-slsk.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smb-browse.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smb-common.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smb-direct.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smb-logon.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smb-mailslot.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smb-pipe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smb-sidsnooping.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smb2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smcr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sml.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smpp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smrse.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-smtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sna.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-snaeth.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sndcp-xid.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sndcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-snmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-socketcan.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-socks.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-soupbintcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-spdy.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-spice.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-spnego.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-spp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-spray.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sprt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-srp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-srvloc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sscf-nni.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sscop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ssh.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ssl-utils.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ssl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sstp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-stanag4607.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-starteam.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-stat-notify.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-stat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-stt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-stun.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sua.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sv.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-swipe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-symantec.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sync.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-synergy.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-synphasor.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sysdig-event.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-sysex.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-syslog.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-t124.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-t125.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-t30.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-t38.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tacacs.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tali.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tapa.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tcap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tcpros.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tdmoe.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tdmop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tds.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-teamspeak2.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-teimanagement.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-teklink.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-telkonet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-telnet.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-teredo.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tetra.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-text-media.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tfp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tftp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-thrift.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-time.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tipc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tivoconnect.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tn3270.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tn5250.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tnef.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tns.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tpkt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tpncp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-trill.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-trmac.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tte-pcf.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tte.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-turbocell.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-turnchannel.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tuxedo.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-tzsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-u3v.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ua.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ua3g.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-uasip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-uaudp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ubertooth.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ucp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-udld.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-udp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-udt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-uftp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-uftp4.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-uhd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ulp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-uma.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-umts_fp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-umts_mac.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usb-audio.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usb-ccid.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usb-com.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usb-dfu.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usb-hid.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usb-hub.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usb-masstorage.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usb-video.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usb.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-usbip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-user_encap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-userlog.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-uts.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-v120.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-v150fw.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-v52.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-v5dl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-v5ef.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-v5ua.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vcdu.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vicp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vines.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vlan.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vmlab.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vnc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vntag.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vp8.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vrrp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vrt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vsip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vssmonitoring.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vuze-dht.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vxi11.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-vxlan.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wai.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wassp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-waveagent.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wbxml.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wccp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-websocket.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wfleet-hdlc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-who.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-whois.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wifi-display.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wifi-p2p.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-windows-common.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-winsrepl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wlancertextn.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wlccp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wol.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wow.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wps.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wreth.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wsmp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wsp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wtls.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-wtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-x11.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-x25.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-x29.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-x2ap.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-x509af.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-x509ce.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-x509if.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-x509sat.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xcsl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xdmcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xip-serval.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xip.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xmcp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xml.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xmpp-conference.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xmpp-core.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xmpp-gtalk.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xmpp-jingle.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xmpp-other.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xmpp-utils.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xmpp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xot.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-xyplex.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-yami.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-yhoo.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ymsg.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ypbind.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-yppasswd.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ypserv.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ypxfr.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-aps.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-nwk-gp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-nwk.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-security.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl-closures.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl-general.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl-ha.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl-hvac.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl-lighting.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl-meas-sensing.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl-misc.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl-sas.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl-se.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zcl.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zdp-binding.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zdp-discovery.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zdp-management.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zbee-zdp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zebra.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zep.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-ziop.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zrtp.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/packet-zvt.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/register.c \
	$(WIRESHARK_SRC_PATH)/epan/dissectors/usb.c


LOCAL_MODULE := libwireshark

LOCAL_C_INCLUDES := \
	$(WIRESHARK_SRC_PATH) \
	$(WIRESHARK_SRC_PATH)/epan \
	$(WIRESHARK_SRC_PATH)/epan/wmem \
	$(WIRESHARK_SRC_PATH)/epan/crypt \
	$(WIRESHARK_SRC_PATH)/epan/ftypes \
	$(WIRESHARK_SRC_PATH)/epan/dfilter \
	$(WIRESHARK_SRC_PATH)/tools/lemon \
	$(WIRESHARK_SRC_PATH)/epan/dissectors \
	$(WIRESHARK_SRC_PATH)/epan/nghttp2 \
	$(LOCAL_PATH)/../libglib-2.0/glib-2.0


LOCAL_CFLAGS := -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I.. -D_FORTIFY_SOURCE=2 -DWS_BUILD_DLL \
	-DG_DISABLE_SINGLE_INCLUDES -DG_DISABLE_DEPRECATED -pthread \
	-Wall -Wextra -Wendif-labels -Wpointer-arith -Wformat-security -fwrapv -fno-strict-overflow \
	-fno-delete-null-pointer-checks -Wvla -Waddress -Wattributes -Wdiv-by-zero -Wignored-qualifiers \
	-Wpragmas -Wno-overlength-strings -Wno-long-long -Wc++-compat -Wdeclaration-after-statement \
	-Wshadow -Wno-pointer-sign -Wold-style-definition -Wstrict-prototypes -Wlogical-op \
	-Wjump-misses-init -fexcess-precision=fast -fvisibility=hidden

include $(BUILD_STATIC_LIBRARY)
