#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test recognition of Shell printf format strings.

escape_backslashes='s/\\/\\\\/g'
LC_ALL=C sed -e "$escape_backslashes" <<\EOF > f-sp-1.data
# Valid: no argument
"abc%%"
# Valid: one character argument
"abc%c"
# Valid: one string argument
"abc%s"
# Valid: one integer argument
"abc%i"
# Valid: one integer argument
"abc%d"
# Valid: one integer argument
"abc%o"
# Valid: one integer argument
"abc%u"
# Valid: one integer argument
"abc%x"
# Valid: one integer argument
"abc%X"
# Valid: one floating-point argument
"abc%e"
# Valid: one floating-point argument
"abc%E"
# Valid: one floating-point argument
"abc%f"
# Valid: one floating-point argument
"abc%F"
# Valid: one floating-point argument
"abc%g"
# Valid: one floating-point argument
"abc%G"
# Valid: one floating-point argument
"abc%a"
# Valid: one floating-point argument
"abc%A"
# Valid: one argument with flags
"abc%0#g"
# Valid: one argument with width
"abc%2g"
# Invalid: one argument with width
"abc%*g"
# Valid: one argument with precision
"abc%.4g"
# Invalid: one argument with precision
"abc%.*g"
# Valid: one argument with width and precision
"abc%14.4g"
# Invalid: one argument with width and precision
"abc%14.*g"
# Invalid: one argument with width and precision
"abc%*.4g"
# Invalid: one argument with width and precision
"abc%*.*g"
# Invalid: unterminated
"abc%"
# Invalid: unknown format specifier
"abc%y"
# Invalid: flags after width
"abc%*0g"
# Valid: null precision
"abc%.f"
# Invalid: twice precision
"abc%.4.2g"
# Valid: three arguments
"abc%d%u%u"
# Valid: a numbered argument
"abc%1$d"
# Invalid: zero
"abc%0$d"
# Valid: two-digit numbered arguments
"abc%11$def%10$dgh%9$dij%8$dkl%7$dmn%6$dop%5$dqr%4$dst%3$duv%2$dwx%1$dyz"
# Invalid: unterminated number
"abc%1"
# Invalid: flags before number
"abc%+1$d"
# Valid: three arguments, two with same number
"abc%1$4x,%2$c,%1$u"
# Invalid: argument with conflicting types
"abc%1$4x,%2$c,%1$s"
# Valid: no conflict
"abc%1$4x,%2$c,%1$u"
# Invalid: mixing of numbered and unnumbered arguments
"abc%d%2$x"
# Valid: numbered argument with constant precision
"abc%1$.9x"
# Invalid: mixing of numbered and unnumbered arguments
"abc%1$.*x"
# Valid: missing non-final argument
"abc%2$x%3$s"
# Valid: permutation
"abc%2$ddef%1$d"
# Valid: multiple uses of same argument
"abc%2$xdef%1$sghi%2$x"
# Invalid: one argument with width
"abc%2$#*1$g"
# Invalid: one argument with width and precision
"abc%3$*2$.*1$g"
# Invalid: zero
"abc%2$*0$.*1$g"
# Invalid: flag not valid
"abc%'d"
# Invalid: flag not valid
"abc%'u"
# Invalid: flag not valid
"abc%'f"
# Invalid: flag not valid
"abc%'g"
# Invalid: flag not valid for specifier
"abc%#c"
# Invalid: flag not valid for specifier
"abc%#s"
# Invalid: flag not valid for specifier
"abc%#i"
# Invalid: flag not valid for specifier
"abc%#d"
# Invalid: flag not valid for specifier
"abc%#u"
# Invalid: flag not valid for specifier
"abc%0c"
# Invalid: flag not valid for specifier
"abc%0s"
# Valid: escape sequence
"abc%%def\\"
# Valid: escape sequence
"abc%%def\a"
# Valid: escape sequence
"abc%%def\b"
# Valid: escape sequence
"abc%%def\f"
# Valid: escape sequence
"abc%%def\n"
# Valid: escape sequence
"abc%%def\r"
# Valid: escape sequence
"abc%%def\t"
# Valid: escape sequence
"abc%%def\v"
# Valid: escape sequence
"abc%%def\066"
# Invalid: escape sequence
"abc%%def\"
# Invalid: escape sequence
"abc%%def\""
# Invalid: escape sequence
"abc%%def\c"
# Invalid: escape sequence
"abc%%def\x32"
# Invalid: escape sequence
"abc%%def\u20ac"
# Invalid: escape sequence
"abc%%def\U0001F41C"
# Invalid: escape sequence
"abc%%def\%d"
EOF

: ${XGETTEXT=xgettext}
n=0
while read comment; do
  # Note: The 'read' command processes backslashes. ('read -r' is not portable.)
  read string
  n=`expr $n + 1`
  escape_backslashes='s/\\/\\\\/g'
  escape_dollars='s/\$/\\\$/g'
  string=`printf '%s\n' "$string" | LC_ALL=C sed -e "$escape_backslashes" -e "$escape_dollars"`
  cat <<EOF > f-sp-1-$n.in
gettext ${string};
EOF
  ${XGETTEXT} -L Shell -o f-sp-1-$n.po f-sp-1-$n.in || Exit 1
  test -f f-sp-1-$n.po || Exit 1
  fail=
  if echo "$comment" | grep 'Valid:' > /dev/null; then
    if grep sh-printf-format f-sp-1-$n.po > /dev/null; then
      :
    else
      fail=yes
    fi
  else
    if grep sh-printf-format f-sp-1-$n.po > /dev/null; then
      fail=yes
    else
      :
    fi
  fi
  if test -n "$fail"; then
    echo "Format string recognition error:" 1>&2
    cat f-sp-1-$n.in 1>&2
    echo "Got:" 1>&2
    cat f-sp-1-$n.po 1>&2
    Exit 1
  fi
  rm -f f-sp-1-$n.in f-sp-1-$n.po
done < f-sp-1.data

Exit 0
