#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test heuristic recognition of D format strings like "100% complete".

cat <<\EOF > f-d-3.d
void func () {
  gettext("Test 1a is 100% complete");
  format(gettext("Test 1b is 100% complete"), 120);
  gettext("Test 2a from 0% complete to 100% complete");
  format(gettext("Test 2b from 0% complete to 100% complete"), 120, 121);
  gettext("Test 3a of %s is 100% complete");
  format(gettext("Test 3b of %s is 100% complete"), "foo", 120);
}
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location -d f-d-3.tmp f-d-3.d || Exit 1
LC_ALL=C tr -d '\r' < f-d-3.tmp.po > f-d-3.po || Exit 1

cat <<\EOF > f-d-3.ok
msgid "Test 1a is 100% complete"
msgstr ""

#, d-format
msgid "Test 1b is 100% complete"
msgstr ""

msgid "Test 2a from 0% complete to 100% complete"
msgstr ""

#, d-format
msgid "Test 2b from 0% complete to 100% complete"
msgstr ""

#, c-format, d-format
msgid "Test 3a of %s is 100% complete"
msgstr ""

#, d-format
msgid "Test 3b of %s is 100% complete"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} f-d-3.ok f-d-3.po
result=$?

exit $result
