#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test processing of POT files that have CRLF as line terminators.

: ${MSGCAT=msgcat}
${MSGCAT} -o mcat-test23.out "$wabs_srcdir"/testdata/crlf.pot || Exit 1

cat <<\EOF > mcat-test23.ok
#: .\edu\templates\edu\home.html:69 .\edu\templates\edu\music_country.html:34
#, python-format
msgid "Hi"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} mcat-test23.ok mcat-test23.out || Exit 1

exit 0
