#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test merging of a message which has plural forms in ref.pot but not
# in def.po.

cat <<\EOF > mm-pl-1.po
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: cog_training 1.0\n"
"POT-Creation-Date: 2001-04-29 22:40+0200\n"
"PO-Revision-Date: 2001-04-29 21:19+02:00\n"
"Last-Translator: Felix N. <xyz@zyx.uucp>\n"
"Language-Team: German <de@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#:foobar.c:29
#, c-format
msgid "%d error"
msgstr "%d erreur"
EOF

cat <<\EOF > mm-pl-1.pot
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2001-04-30 18:51+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#:foobar.c:32
#, c-format
msgid "%d error"
msgid_plural "%d errors"
msgstr[0] ""
msgstr[1] ""
EOF

: ${MSGMERGE=msgmerge}
${MSGMERGE} -q -o mm-pl-1.tmp mm-pl-1.po mm-pl-1.pot || Exit 1
LC_ALL=C tr -d '\r' < mm-pl-1.tmp > mm-pl-1.out || Exit 1

cat <<\EOF > mm-pl-1.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: cog_training 1.0\n"
"POT-Creation-Date: 2001-04-30 18:51+0200\n"
"PO-Revision-Date: 2001-04-29 21:19+02:00\n"
"Last-Translator: Felix N. <xyz@zyx.uucp>\n"
"Language-Team: German <de@li.org>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: foobar.c:32
#, fuzzy, c-format
msgid "%d error"
msgid_plural "%d errors"
msgstr[0] "%d erreur"
msgstr[1] "%d erreur"
EOF

: ${DIFF=diff}
${DIFF} mm-pl-1.ok mm-pl-1.out
result=$?

exit $result
