#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test validation of POT file with non-ASCII messages.

cat <<\EOF > mm-ch-4.po
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Bruno Haible <bruno@clisp.org>, 2024.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: 2024-10-13 18:36+0200\n"
"Last-Translator: Bruno Haible <bruno@clisp.org>\n"
"Language-Team: French <traduc@traduc.org>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

msgid "You can find me résumé at <%s>."
msgstr "Vous trouvez mon CV sous <%s>."
EOF

: ${MSGMERGE=msgmerge}
${MSGMERGE} -q -o mm-ch-4.tmp.po mm-ch-4.po "$wabs_srcdir"/testdata/nonascii.pot
test $? = 1 || Exit 1
