#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test merging of a ref.pot in UTF-8 encoding against a def.po in legacy
# encoding (that was produced from an older version of ref.pot, in ASCII
# encoding).

cat <<\EOF > mm-ch-2-ru.po
# Russian messages for CLISP
# Copyright (C) 1998 Free Software Foundation, Inc.
# Eduard Haritonov <hed@iis.nsk.su>, 1998.
# Arseny Slobodjuck <ampy@ich.dvo.ru>, 2002.
#
msgid ""
msgstr ""
"Project-Id-Version: GNU elvis 1.7\n"
"POT-Creation-Date: 2002-11-01 01:22+0100\n"
"PO-Revision-Date: 2002-11-01 01:23+0100\n"
"Last-Translator: Arseny Slobodjuck <ampy@ich.dvo.ru>\n"
"Language-Team: Russian <ru@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=koi8-r\n"
"Content-Transfer-Encoding: 8bit\n"

#: arith.c:9
msgid "Division durch Null"
msgstr "ƒ≈Ã≈Œ…≈ Œ¡ Œ’Ãÿ"
EOF

cat <<\EOF > mm-ch-2.pot
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2002-11-01 01:22+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: arith.c:10
msgid "Division durch Null"
msgstr ""

#: arith.c:15
msgid "√úberlauf"
msgstr ""
EOF

: ${MSGMERGE=msgmerge}
${MSGMERGE} -q -o mm-ch-2.tmp mm-ch-2-ru.po mm-ch-2.pot || Exit 1
LC_ALL=C tr -d '\r' < mm-ch-2.tmp > mm-ch-2.out || Exit 1

cat <<\EOF > mm-ch-2.ok
# Russian messages for CLISP
# Copyright (C) 1998 Free Software Foundation, Inc.
# Eduard Haritonov <hed@iis.nsk.su>, 1998.
# Arseny Slobodjuck <ampy@ich.dvo.ru>, 2002.
#
msgid ""
msgstr ""
"Project-Id-Version: GNU elvis 1.7\n"
"POT-Creation-Date: 2002-11-01 01:22+0100\n"
"PO-Revision-Date: 2002-11-01 01:23+0100\n"
"Last-Translator: Arseny Slobodjuck <ampy@ich.dvo.ru>\n"
"Language-Team: Russian <ru@li.org>\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: arith.c:10
msgid "Division durch Null"
msgstr "–¥–µ–ª–µ–Ω–∏–µ –Ω–∞ –Ω—É–ª—å"

#: arith.c:15
msgid "√úberlauf"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} mm-ch-2.ok mm-ch-2.out
result=$?

exit $result
