#!/bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test C support: --add-comments option.

cat <<\EOF > xg-c-16.c
/* a */
/* b */ char *string = /* c */
/* d */
/* e */ _( /* f */ "hello " /* g */ "world" /* h */ );
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --add-comments --omit-header --no-location --keyword=_ \
  -d xg-c-16.tmp xg-c-16.c || Exit 1
LC_ALL=C tr -d '\r' < xg-c-16.tmp.po > xg-c-16.po || Exit 1

cat <<EOF > xg-c-16.ok
#. a
#. b
#. c
#. d
#. e
#. f
msgid "hello world"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-c-16.ok xg-c-16.po
result=$?

exit $result
