#!/bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test of *.desktop files with non-default keywords (used by KDE).

cat <<\EOF > hello.desktop
[Desktop Entry]
Name=Hello
Description=A friendly greeting program
TryExec=hello
Exec=hello
Icon=handshake.jpg
Type=Application
Keywords=Utility;
EOF

: ${XGETTEXT=xgettext}

${XGETTEXT} --keyword=Description -o xg-de-3-1.tmp hello.desktop || Exit 1
func_filter_POT_Creation_Date xg-de-3-1.tmp hello-desktop-1.pot

${XGETTEXT} --keyword= --keyword=Description -o xg-de-3-2.tmp hello.desktop || Exit 1
func_filter_POT_Creation_Date xg-de-3-2.tmp hello-desktop-2.pot

cat <<\EOF > hello-desktop-1.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: hello.desktop:2
msgid "Hello"
msgstr ""

#: hello.desktop:3
msgid "A friendly greeting program"
msgstr ""

#: hello.desktop:8
msgid "Utility;"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} hello-desktop-1.ok hello-desktop-1.pot || Exit 1

cat <<\EOF > hello-desktop-2.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: hello.desktop:3
msgid "A friendly greeting program"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} hello-desktop-2.ok hello-desktop-2.pot || Exit 1
