#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test C support: --add-comments option.

cat <<EOF > xg-c-6.in.C
/* This comment will not be extracted.  */
gettext ("help");

/*   XXX: But this one will.  */
gettext_noop ("me");

//XXX: ..and this
dcgettext ("foo", "quick", LC_MESSAGES);

  /* not not not */
dgettext ("bar", "!");
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location --add-comments=XXX \
  -d xg-c-6.tmp xg-c-6.in.C || Exit 1
LC_ALL=C tr -d '\r' < xg-c-6.tmp.po > xg-c-6.po || Exit 1

cat <<EOF > xg-c-6.ok
msgid "help"
msgstr ""

#. XXX: But this one will.
msgid "me"
msgstr ""

#. XXX: ..and this
msgid "quick"
msgstr ""

msgid "!"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-c-6.ok xg-c-6.po
result=$?

exit $result
