#!/bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test Perl support: --add-comments option, strings with embedded expressions.

cat <<\EOF > xg-pl-5.pl
# This comment will not be extracted.
print gettext "help";
#  TRANSLATORS: This is an extracted comment.
print gettext "me";
# Not extracted either.
print gettext "Hey Jude";
# TRANSLATORS:
#    Nickname of the Beatles
print gettext "The Fabulous Four";
# Strings with embedded expressions, a.k.a. interpolated strings.
print gettext "embedded_1_$foo bar";
print gettext "embedded_2_${foo}bar";
print gettext "embedded_3_$array[func(gettext 'embedded_3_sub1')]_bar_$array[func(gettext 'embedded_3_sub2')]_baz";
print gettext "embedded_4";
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location --add-comments=TRANSLATORS: \
  -d xg-pl-5.tmp xg-pl-5.pl || Exit 1
LC_ALL=C tr -d '\r' < xg-pl-5.tmp.po > xg-pl-5.po || Exit 1

cat <<\EOF > xg-pl-5.ok
msgid "help"
msgstr ""

#. TRANSLATORS: This is an extracted comment.
msgid "me"
msgstr ""

msgid "Hey Jude"
msgstr ""

#. TRANSLATORS:
#. Nickname of the Beatles
msgid "The Fabulous Four"
msgstr ""

msgid "embedded_3_sub1"
msgstr ""

msgid "embedded_3_sub2"
msgstr ""

msgid "embedded_4"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-pl-5.ok xg-pl-5.po
result=$?

exit $result
