#!/bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test of Tcl support: escape sequences.

cat <<\EOF > xg-t-4.tcl
puts [_ "Hello\u200e\u201cWorld\u201d"]
puts [_ "x\u20y\x20z"]
puts [_ "\xFF20"]
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --add-comments --no-location -k_ -o xg-t-4.tmp xg-t-4.tcl 2>xg-t-4.err
test $? = 0 || { cat xg-t-4.err; Exit 1; }
# Don't simplify this to "grep ... < xg-t-4.tmp", otherwise OpenBSD 4.0 grep
# only outputs "Binary file (standard input) matches".
cat xg-t-4.tmp | grep -v 'POT-Creation-Date' | LC_ALL=C tr -d '\r' > xg-t-4.pot

cat <<\EOF > xg-t-4.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "Hello‎“World”"
msgstr ""

msgid "x y z"
msgstr ""

msgid " "
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-t-4.ok xg-t-4.pot
result=$?

exit $result
