#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test Vala support: printf and format strings.

: ${XGETTEXT=xgettext}

cat <<\EOF > xg-vala-6.vala
"<b>%s</b>".printf(_("Hello 1"));
_("Explanation: %s").printf(_("Hello 2"));
_("test case 1");
_("test case 2").printf();
(_("test case 3"));
(_("test case 4")).printf();
((_("test case 5")));
((_("test case 6"))).printf();
return _("test case 10");
return _("test case 11").printf();
return (_("test case 12").printf());
return (_("test case 13")).printf();
foo (_("test case 15"));
foo (_("test case 16")).printf();
(foo (_("test case 17"))).printf();
(foo (_("test case 18")).printf());
foo (_("test case 19").printf());
foo + _("test case 20");
foo + _("test case 21").printf();
(foo + _("test case 22")).printf();
_("test case 23") + foo;
_("test case 24").printf() + foo;
(_("test case 25") + foo).printf();
_("test case 26 a") + _("test case 26 b");
_("test case 27 a").printf() + _("test case 27 b");
_("test case 28 a") + _("test case 28 b").printf();
_("test case 29 a").printf() + _("test case 29 b").printf();
(_("test case 30 a") + _("test case 30 b")).printf();
return _("test case 31 a") + _("test case 31 b");
return _("test case 32 a").printf() + _("test case 32 b");
return _("test case 33 a") + _("test case 33 b").printf();
return _("test case 34 a").printf() + _("test case 34 b").printf();
return (_("test case 35 a") + _("test case 35 b")).printf();
return _("test case 36 a") + (_("test case 36 b")).printf() + _("test case 36 c").printf();
return _("test case 37 a") + _("test case 37 b").printf() + (_("test case 37 c")).printf();
return _("test case 38 a") + (_("test case 38 b")).printf() + (_("test case 38 c")).printf();
foo ? _("test case 40 a") : _("test case 40 b");
foo ? _("test case 41 a").printf() : _("test case 41 b");
foo ? _("test case 42 a") : _("test case 42 b").printf();
foo ? _("test case 43 a").printf() : _("test case 43 b").printf();
(foo ? _("test case 44 a") : _("test case 44 b"));
(foo ? _("test case 45 a") : _("test case 45 b")).printf();
s = (_("test case 46")).printf();
(s = _("test case 47")).printf();
s += (_("test case 48")).printf();
(s += _("test case 49")).printf();
return _("test case 50 a")
       + _("test case 50 b").printf()
       + (_("test case 50 c")).printf()
       + foo(_("test case 50 d")).printf()
       + (b ? _("test case 50 e") : _("test case 50 f")).printf()
       + (b ? foo + _("test case 50 g") : _("test case 50 h") + bar).printf();
Posix.printf(_("Hello 3"));
Posix.printf(_("Hello 4 %s!"), _("Sir"));
EOF

${XGETTEXT} --omit-header --no-location -o xg-vala-6.tmp xg-vala-6.vala || Exit 1
func_filter_POT_Creation_Date xg-vala-6.tmp xg-vala-6.po

cat <<\EOF > xg-vala-6.ok
msgid "Hello 1"
msgstr ""

#, c-format
msgid "Explanation: %s"
msgstr ""

msgid "Hello 2"
msgstr ""

msgid "test case 1"
msgstr ""

#, c-format
msgid "test case 2"
msgstr ""

msgid "test case 3"
msgstr ""

#, c-format
msgid "test case 4"
msgstr ""

msgid "test case 5"
msgstr ""

#, c-format
msgid "test case 6"
msgstr ""

msgid "test case 10"
msgstr ""

#, c-format
msgid "test case 11"
msgstr ""

#, c-format
msgid "test case 12"
msgstr ""

#, c-format
msgid "test case 13"
msgstr ""

msgid "test case 15"
msgstr ""

msgid "test case 16"
msgstr ""

msgid "test case 17"
msgstr ""

msgid "test case 18"
msgstr ""

#, c-format
msgid "test case 19"
msgstr ""

msgid "test case 20"
msgstr ""

#, c-format
msgid "test case 21"
msgstr ""

msgid "test case 22"
msgstr ""

msgid "test case 23"
msgstr ""

#, c-format
msgid "test case 24"
msgstr ""

msgid "test case 25"
msgstr ""

msgid "test case 26 a"
msgstr ""

msgid "test case 26 b"
msgstr ""

#, c-format
msgid "test case 27 a"
msgstr ""

msgid "test case 27 b"
msgstr ""

msgid "test case 28 a"
msgstr ""

#, c-format
msgid "test case 28 b"
msgstr ""

#, c-format
msgid "test case 29 a"
msgstr ""

#, c-format
msgid "test case 29 b"
msgstr ""

msgid "test case 30 a"
msgstr ""

msgid "test case 30 b"
msgstr ""

msgid "test case 31 a"
msgstr ""

msgid "test case 31 b"
msgstr ""

#, c-format
msgid "test case 32 a"
msgstr ""

msgid "test case 32 b"
msgstr ""

msgid "test case 33 a"
msgstr ""

#, c-format
msgid "test case 33 b"
msgstr ""

#, c-format
msgid "test case 34 a"
msgstr ""

#, c-format
msgid "test case 34 b"
msgstr ""

msgid "test case 35 a"
msgstr ""

msgid "test case 35 b"
msgstr ""

msgid "test case 36 a"
msgstr ""

#, c-format
msgid "test case 36 b"
msgstr ""

#, c-format
msgid "test case 36 c"
msgstr ""

msgid "test case 37 a"
msgstr ""

#, c-format
msgid "test case 37 b"
msgstr ""

#, c-format
msgid "test case 37 c"
msgstr ""

msgid "test case 38 a"
msgstr ""

#, c-format
msgid "test case 38 b"
msgstr ""

#, c-format
msgid "test case 38 c"
msgstr ""

msgid "test case 40 a"
msgstr ""

msgid "test case 40 b"
msgstr ""

#, c-format
msgid "test case 41 a"
msgstr ""

msgid "test case 41 b"
msgstr ""

msgid "test case 42 a"
msgstr ""

#, c-format
msgid "test case 42 b"
msgstr ""

#, c-format
msgid "test case 43 a"
msgstr ""

#, c-format
msgid "test case 43 b"
msgstr ""

msgid "test case 44 a"
msgstr ""

msgid "test case 44 b"
msgstr ""

#, c-format
msgid "test case 45 a"
msgstr ""

#, c-format
msgid "test case 45 b"
msgstr ""

#, c-format
msgid "test case 46"
msgstr ""

#, c-format
msgid "test case 47"
msgstr ""

#, c-format
msgid "test case 48"
msgstr ""

msgid "test case 49"
msgstr ""

msgid "test case 50 a"
msgstr ""

#, c-format
msgid "test case 50 b"
msgstr ""

#, c-format
msgid "test case 50 c"
msgstr ""

msgid "test case 50 d"
msgstr ""

#, c-format
msgid "test case 50 e"
msgstr ""

#, c-format
msgid "test case 50 f"
msgstr ""

msgid "test case 50 g"
msgstr ""

msgid "test case 50 h"
msgstr ""

msgid "Hello 3"
msgstr ""

#, c-format
msgid "Hello 4 %s!"
msgstr ""

msgid "Sir"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-vala-6.ok xg-vala-6.po
result=$?

exit $result
