#!/bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test C support: --add-comments option.

cat <<EOF > xg-c-9.c
// This comment will not be extracted.
print (gettext ("help"));
//  TRANSLATORS: This is an extracted comment.
print (gettext ("me"));
/* Not extracted either. */
print (gettext ("Hey Jude"));
/*  TRANSLATORS:
     Nickname of the Beatles
*/
print (gettext ("The Fabulous Four"));
/* TRANSLATORS: The strings get concatenated.  */
print (gettext ("there is not enough"
" room on a single line for this entire long, " // confusing, eh?
"verbose string"));
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location --add-comments=TRANSLATORS: \
  -d xg-c-9.tmp xg-c-9.c || Exit 1
LC_ALL=C tr -d '\r' < xg-c-9.tmp.po > xg-c-9.po || Exit 1

cat <<EOF > xg-c-9.ok
msgid "help"
msgstr ""

#. TRANSLATORS: This is an extracted comment.
msgid "me"
msgstr ""

msgid "Hey Jude"
msgstr ""

#. TRANSLATORS:
#. Nickname of the Beatles
#.
msgid "The Fabulous Four"
msgstr ""

#. TRANSLATORS: The strings get concatenated.
msgid ""
"there is not enough room on a single line for this entire long, verbose "
"string"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-c-9.ok xg-c-9.po
result=$?

exit $result
