#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test PO extractor with non-ASCII input file with header entry and
# --exclude-file option.

cat <<\EOF > xg-po-5.exclusions
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "no"
msgstr ""
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --no-location -d xg-po-5.tmp --exclude-file xg-po-5.exclusions \
            "$wabs_srcdir"/testdata/xg-po-3.po \
  || Exit 1
func_filter_POT_Creation_Date xg-po-5.tmp.po xg-po-5.pot

cat <<\EOF > xg-po-5.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "ü"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-po-5.ok xg-po-5.pot || Exit 1

Exit 0
