#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test extraction of non-ASCII msgids.

cat <<\EOF > xg-sc-5.scm
(define (foo option)
  (display (format (_ "nezn·m˝ p¯epÌnaË -- ~A\n") option))
  (display (format (_ "p¯epÌnaË vyæaduje argument -- ~A\n") option)))
}
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --no-location -k_ -o xg-sc-5.po xg-sc-5.scm 2>/dev/null
test $? = 1 || { Exit 1; }
${XGETTEXT} --no-location -k_ --from-code=iso-8859-2 -o xg-sc-5.tmp xg-sc-5.scm || Exit 1
LC_ALL=C tr -d '\r' < xg-sc-5.tmp > xg-sc-5.po || Exit 1

sed -e '/POT-Creation-Date/d' < xg-sc-5.po > xg-sc-5.pot

cat <<\EOF > xg-sc-5.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#, scheme-format
msgid "nezn√°m√Ω p≈ôep√≠naƒç -- ~A\n"
msgstr ""

#, scheme-format
msgid "p≈ôep√≠naƒç vy≈æaduje argument -- ~A\n"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-sc-5.ok xg-sc-5.pot
result=$?

exit $result
