#! /bin/sh
# Script for fetching the PO files, produced by translators, from a
# translations project's site on the internet, to the current directory.
#
# Copyright (C) 2025 Free Software Foundation, Inc.
# This file is free software; the Free Software Foundation gives
# unlimited permission to use, copy, distribute, and modify it.

# Usage: ./fetch-po
#
# This script is invoked from two locations:
# 1. From the script that fetches auxiliary files that are omitted from
#    the version control repository of this package, typically called
#    'autopull.sh' or 'bootstrap --pull' or similar.
# 2. From the Makefile in the po/ directory, target 'fetch-po'.

# There are two ways to implement this script:
#
# In packages whose translators commit their PO files directly into
# the version control of the package, or where a translations project's
# daemon does this automatically on behalf of the translators, this
# script does not do anything.
echo "fetch-po: Nothing to do."
#
# In packages where the translations are collected by a translation project,
# use a 'po-fetch' invocation.
# See 'po-fetch --help' for the possible arguments.
# If you want the fetched PO files to be added into the version control of
# the package, use the option '--git'; otherwise, don't use this option.
#po-fetch ...
